//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaktus.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CactusExhibitions
    {
        public int Id { get; set; }
        public Nullable<int> CactusId { get; set; }
        public Nullable<int> ExhibitionId { get; set; }
    
        public virtual Cacti Cacti { get; set; }
        public virtual Exhibitions Exhibitions { get; set; }
    }
}
