//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaktus.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cacti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cacti()
        {
            this.CactusExhibitions = new HashSet<CactusExhibitions>();
        }
    
        public int Id { get; set; }
        public string Вид { get; set; }
        public string Происхождение { get; set; }
        public Nullable<int> Возраст { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public string Инструкции_по_уходу { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CactusExhibitions> CactusExhibitions { get; set; }
    }
}
