//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaktus.DBMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exhibitions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exhibitions()
        {
            this.CactusExhibitions = new HashSet<CactusExhibitions>();
        }
    
        public int Id { get; set; }
        public string Название { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Место_проведения { get; set; }
        public string Награды { get; set; }
        public string Комментарии { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CactusExhibitions> CactusExhibitions { get; set; }
    }
}
